### ISSUE TITLE
Single player crash - io.github.elytra.copo.client.gui.GuiDrive.func

### ISSUE THREAD

**Issue by ProsperCraft** [elytra/CorrelatedPotentialistics#51]
https://gist.github.com/ProsperCraft/f034a90017320154b86a55e2afa1b273

This is funny, I was setting up a test environment to troubleshoot a dupe with sponge.

I was setting it up in a flat world with no other mods, and got this crash.

ava.lang.NullPointerException: Rendering screen
    at io.github.elytra.copo.client.gui.GuiDrive.func_146979_b(GuiDrive.java:87)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:114)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

**Comment by ProsperCraft** [comment]
I was trying to click a 64k drive into a storage.

**Comment by ProsperCraft** [comment]
I think I realized what I just did, I put the 64 miB Drive inside of its own gui, which I am unable to reproduce.

**Comment by ProsperCraft** [comment]
I am in creative.
